name: algoliasearch-django

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          # django 4.0
          - version: "3.8.20"
            toxenv: py38-django40
            os: ubuntu-20.04
          - version: "3.9.20"
            toxenv: py39-django40
            os: ubuntu-20.04
          - version: "3.10.15"
            toxenv: py310-django40
            os: ubuntu-20.04
          # django 4.1
          - version: "3.8.20"
            toxenv: py38-django41
            os: ubuntu-20.04
          - version: "3.9.20"
            toxenv: py39-django41
            os: ubuntu-20.04
          - version: "3.10.15"
            toxenv: py310-django41
            os: ubuntu-20.04
          - version: "3.11.10"
            toxenv: py311-django41
            os: ubuntu-20.04
          # django 4.2
          - version: "3.8.20"
            toxenv: py38-django42
            os: ubuntu-20.04
          - version: "3.9.20"
            toxenv: py39-django42
            os: ubuntu-20.04
          - version: "3.10.15"
            toxenv: py310-django42
            os: ubuntu-20.04
          - version: "3.11.10"
            toxenv: py311-django42
            os: ubuntu-20.04
          - version: "3.12.7"
            toxenv: py312-django42
            os: ubuntu-20.04
          # django 5.0
          - version: "3.10.15"
            toxenv: py310-django50
            os: ubuntu-20.04
          - version: "3.11.10"
            toxenv: py311-django50
            os: ubuntu-20.04
          - version: "3.12.7"
            toxenv: py312-django50
            os: ubuntu-20.04
          # django 5.1
          - version: "3.10.15"
            toxenv: py310-django51
            os: ubuntu-20.04
          - version: "3.11.10"
            toxenv: py311-django51
            os: ubuntu-20.04
          - version: "3.12.7"
            toxenv: py312-django51
            os: ubuntu-20.04
          - version: "3.13.0"
            toxenv: py313-django51
            os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies and run tests
      run: |
        python -m venv python-ci-run
        source python-ci-run/bin/activate
        python -m pip install --upgrade pip
        python -m pip install tox
        python -m pip install -r requirements.txt
        TOXENV=${{ matrix.toxenv }} ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }} tox
